# 2.1.1 入门

In [ ]:

import torch
x = torch.arange(12)      #arange（start，end，step）得到[start，end）就是Tensor版的range()
print(x)
print(x.shape)
print(x.numel())          # number of elements
print(x.reshape(3, 4))    #reshape可以把张量x从形状为（12，）的行向量转换为形状为（3，4）的矩阵——3行4列
print(x.reshape(3, -1))   # -1 means infer the dimension
print(x.reshape(-1, 4))   # -1 可省去计算直接补充完整

# 创造全0初始化矩阵
print(torch.zeros(2,3,4)) # zeros函数创建一个全0的矩阵，参数是一个元组，指定了矩阵的形状

# 创造全1初始化矩阵
print(torch.ones(2,3,4))  # ones函数创建一个全1的矩阵，参数是一个元组，指定了矩阵的形状

# 创造全随机初始化矩阵
print(torch.rand(3,4))    # rand函数创建一个全随机的矩阵，参数是一个元组，指定了矩阵的形状

# 创造全随机整数初始化矩阵
print(torch.randint(0,10,(3,4))) # randint函数创建一个全随机整数的矩阵，torch.randint(low, high, size)

# 提供包含数值的 python列表，来为张量中等每个元素赋予确定值
print(torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])) # tensor函数创建一个张量，参数是一个嵌套的Python列表，指定了张量的值和形状


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[0.2688, 0.6548, 0.1265, 0.0747],
        [0.1576, 0.5132, 0.0339, 0.0844],
        [0.9709, 0.8017, 0.7890, 0.7299]])
tensor([[0, 5, 2, 4],
        [7, 7, 6, 1],
        [5, 5, 5, 5]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


# 2.1.2 运算符

In [ ]:

x = torch.tensor([1.0, 2, 4,8])  # 这里的1.0是float类型，其他是int类型，PyTorch会自动把它们转换成同一类型（float），以便进行运算 所以输出是3./4.
y = torch.tensor([2.0, 2, 2, 2])
print(x + y, x - y, x * y, x / y, x ** y, sep = "\n") # 加减乘除幂运算
# pytorch默认最多保留四位小数
print(x == y, x > y, x < y, sep = "\n") # 比较运算符    
print(torch.exp(x)) 
# e+n = × 10ⁿ 2.7183e+00 = 2.7183 × 10⁰
print(x.sum()) # 求和

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([False,  True, False, False])
tensor([False, False,  True,  True])
tensor([ True, False, False, False])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor(15.)


In [55]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
# cat函数在指定维度上连接两个张量，参数是一个包含要连接的张量的元组，以及dim参数指定连接的维度
# 形状必须要一样！
print(torch.cat((x, y), dim=0)) # 沿着**第 0 维（行）**连接
print(torch.cat((x, y), dim=1)) # 沿着**第 1 维（列）**连接
# 连接多个张量
t1 = torch.tensor([[1, 2]])
t2 = torch.tensor([[3, 4]])
t3 = torch.tensor([[5, 6]])
result = torch.cat((t1, t2, t3), dim=0)  # 可以连接3个或更多
print(result)  # 输出：tensor([[1, 2], [3, 4], [5, 6]])    
# 1D 张量连接
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(torch.cat((a, b), dim=0))  # tensor([1, 2, 3, 4, 5, 6])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2, 3, 4, 5, 6])


# 2.1.3 广播机制
核心思想
当两个张量形状不同时，PyTorch 会自动扩展较小的张量，使其与较大张量的形状兼容，然后再进行运算

In [56]:
#  例 1：标量与张量
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 形状 (2, 3)
scalar = 10
result = x + scalar  
# scalar 自动广播成 (2, 3)
#10 →
#[[10, 10, 10],
#[10, 10, 10]]
print(result)  



# 例 2：行向量与矩阵
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])           # 形状 (2, 3)
y = torch.tensor([10, 20, 30])          # 形状 (3,)
result = x + y
# y 自动扩展为 [[10, 20, 30], [10, 20, 30]]，形状变为 (2, 3)
# 结果：[[11, 22, 33], [14, 25, 36]]
print(result)



# 例 3：列向量与矩阵
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])           # 形状 (2, 3)
y = torch.tensor([[10], [20]])          # 形状 (2, 1)
result = x + y
# y 自动扩展为 [[10, 10, 10], [20, 20, 20]]，形状变为 (2, 3)
# 结果：[[11, 12, 13], [24, 25, 26]]
print(result)



# 例 4：不同形状的矩阵  
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])              # 形状 (3, 2)
y = torch.tensor([10, 20])              # 形状 (2,)
result = x * y
print(result)
# y 自动扩展为 [[10, 20], [10, 20], [10, 20]]，形状变为 (3, 2)
# 结果：[[10, 40], [30, 80], [50, 120]]


# 例 5：不同形状的矩阵（成功示例）
x = torch.tensor([[1, 2, 3]])      # 形状 (1, 3)
y = torch.tensor([[1], [2], [3]])  # 形状 (3, 1)
z = x + y  # ✅ 成功！都广播成 (3, 3)
print(z)
# x 自动扩展为 [[1, 2, 3], [1, 2, 3], [1, 2, 3]]，形状变为 (3, 3)
# y 自动扩展为 [[1, 1, 1], [2, 2, 2], [3, 3, 3]]，形状变为 (3, 3)
# 结果：[[2, 3, 4], [3, 4, 5], [4, 5, 6]]   

# 例 6：不同形状的矩阵（错误示例）
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])           # 形状 (2, 3)
y = torch.tensor([10, 20])              # 形状 (2,)
try:
    result = x + y
except RuntimeError as e:
    print("错误：", e)
# 由于 y 的形状 (2,) 无法与 x 的形状 (2, 3) 进行广播，导致运行时错误。广播规则要求两个张量在每个维度上要么相等，要么其中一个为 1，才能进行广播
# 错误案例
a = torch.randn(3, 4)              # 形状 (3, 4)
b = torch.randn(3, 5)              # 形状 (3, 5)
# c = a + b  # ❌ RuntimeError! 第二维 4 != 5

tensor([[11, 12, 13],
        [14, 15, 16]])
tensor([[11, 22, 33],
        [14, 25, 36]])
tensor([[11, 12, 13],
        [24, 25, 26]])
tensor([[ 10,  40],
        [ 30,  80],
        [ 50, 120]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
错误： The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1


# 2.1.4 索引和切片

1、基本索引（按维度取元素）：和 Python 列表类似，使用方括号。
   - `x[i]`：第 i 行（对 2D 张量）。
   - `x[i, j]`：第 i 行第 j 列（标量）。

2、负索引：从末尾计数，`-1` 表示最后一项。
   - `x[-1]` 等同于 `x[x.shape[0]-1]`。

3、切片（slice）：使用 `start:stop:step`，`stop` 不包含。
   - `x[:, 0]`：取所有行的第 0 列（结果是一维张量）。
   - `x[0:2, 0:2]`：取前两行前两列，得到子矩阵。

4、修改切片：大多数切片返回 view（共享内存），修改切片会影响原张量。
   - 如果需要独立副本，使用 `clone()`。

5、常见用法：行、列、元素和子矩阵的访问与赋值。

In [59]:
# 2.1.4 索引和切片
x = torch.tensor([[1.0, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print()

print("x[0] =", x[0])            # 第 0 行
print("x[1] =", x[1])            # 第 1 行
print("x[-1] =", x[-1])          # 最后一行
print()

print("x[0, 0] =", x[0, 0])      # 行列索引访问单个元素
print("x[0, 1] =", x[0, 1])
print()

print("x[:, 0] =", x[:, 0])      # 取第 0 列
print("x[:, 1] =", x[:, 1])      # 取第 1 列
print("x[:, 2] =", x[:, 2])      # 取第 2 列
print()

print("x[0:2, 0:2] =")           # 取前两行前两列
print(x[0:2, 0:2])
print()

# 修改单个元素
x[0, 0] = 10
print("after x[0,0] = 10")
print(x)
print()

# 通过切片一次修改多个元素
x[0:2, 0:2] = torch.tensor([[1.0, 2], [3, 4]])
print("after x[0:2, 0:2] = [[1,2],[3,4]]")
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

x[0] = tensor([1., 2., 3.])
x[1] = tensor([4., 5., 6.])
x[-1] = tensor([7., 8., 9.])

x[0, 0] = tensor(1.)
x[0, 1] = tensor(2.)

x[:, 0] = tensor([1., 4., 7.])
x[:, 1] = tensor([2., 5., 8.])
x[:, 2] = tensor([3., 6., 9.])

x[0:2, 0:2] =
tensor([[1., 2.],
        [4., 5.]])

after x[0,0] = 10
tensor([[10.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

after x[0:2, 0:2] = [[1,2],[3,4]]
tensor([[1., 2., 3.],
        [3., 4., 6.],
        [7., 8., 9.]])


# 2.1.6 转换为其他python对象

In [ ]:

a = torch.tensor([1.0, 2.0, 3.0])
print(a)
print(a.tolist())  # 转换为Python列表
print(a.numpy())   # 转换为NumPy数组
print(a.item() if a.numel() == 1 else "Cannot use item() on multi-element tensor")
print(float(a[0]))
print(int(a[0]))
# item() 只能用于包含单个元素的张量，返回该元素的值作为一个Python标量

tensor([1., 2., 3.])
[1.0, 2.0, 3.0]
[1. 2. 3.]
Cannot use item() on multi-element tensor
1.0
1
