# 2.3.1 标量


In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

# 2.3.2 向量



In [4]:
x = torch.arange(4)
print(x)
print(x[3])
print(x[-1])
print(len(x))
print(x.shape)
print(x.shape[0])

tensor([0, 1, 2, 3])
tensor(3)
tensor(3)
4
torch.Size([4])
4


# 2.3.3 矩阵


In [6]:
A = torch.arange(20).reshape(5, 4)
print(A)
# 转置：行列互换
print(A.T)
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B == B.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# 2.3.4 张量

In [7]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

# 2.3.5 张量算法的基本性质

In [ ]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print(A + B)
print(A * B) # a11 * b11


tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [12]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(X)
print(a + X)
print(a * X)
print((a * X).shape)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])
torch.Size([2, 3, 4])


# 2.3.6 降维

In [17]:
x = torch.arange(4, dtype=torch.float32)
print(x, x.sum())
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A)
print(A.sum(),A.shape)

tensor([0., 1., 2., 3.]) tensor(6.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor(190.) torch.Size([5, 4])


In [ ]:
# axis=0 → 压缩"行" → 结果数量 = 列数  就是沿着行的方向拍扁
A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0, A_sum_axis0.shape)
# axis=1 → 压缩"列" → 结果数量 = 行数
A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1, A_sum_axis1.shape)
print(A.sum(axis=[0, 1])) # axis=[0, 1] → 压缩"行"和"列" → 结果数量 = 1 与 A.sum() 等价
print(A.mean(), A.sum() )
print(A.mean(axis=0), A.sum(axis=0)) # mean(axis=0) → 沿着行的方向拍扁，求平均值

tensor([40., 45., 50., 55.]) torch.Size([4])
tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])
tensor(190.)
tensor(9.5000) tensor(190.)
tensor([ 8.,  9., 10., 11.]) tensor([40., 45., 50., 55.])


In [27]:
# 非降维求和（有时在求和的时候保持维度不变也很有必要）
print(A, A.shape, sep = "\n")
# 非降维
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A, sum_A.shape,sep = "\n") # keepdims=True → 保持维度不变，结果数量 = 行数
# 普通
sum = A.sum(axis=1)
print(sum, sum.shape, sep = "\n")

print(A / sum_A) # A / sum_A → 广播机制：sum_A的列数为1，A的列数为4，sum_A会自动复制4份与A进行逐元素除法


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
torch.Size([5, 4])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
torch.Size([5, 1])
tensor([ 6., 22., 38., 54., 70.])
torch.Size([5])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [ ]:
# 累积总和（就像银行账单的余额一样，每一行的结果都是前面所有行的和）
A.cumsum(axis=0)
# 结果行0 = 行0本身        = [ 0,  1,  2,  3]
# 结果行1 = 行0 + 行1      = [ 4,  6,  8, 10]
# 结果行2 = 行0+行1+行2    = [12, 15, 18, 21]
# 结果行3 = 前四行相加      = [24, 28, 32, 36]
# 结果行4 = 前五行相加      = [40, 45, 50, 55]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

# 2.3.7 点积（Dot Product）


In [30]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y),torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

# 2.3.8 矩阵-向量积

In [31]:
A, x,A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

# 2.3.9 矩阵-矩阵乘法

In [32]:
B = torch.ones(4, 3)
torch.mm(A, B)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

# 2.3.10 范数

In [34]:
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum()

(tensor(5.), tensor(7.))

In [ ]:
torch.ones((4, 9)),torch.norm(torch.ones((4, 9))) # 矩阵元素平方和的平方根(1+1+...+1)^(1/2) = sqrt(36) = 6

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))